# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        web:
            entity:
                class: AppBundle:User
                property: phone

    firewalls:
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false

        main:
            http_basic: ~
            anonymous: ~
            security: true
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /

            logout:
                path:   /logout
                target: /

    access_control:
              - { path: ^/admin, role:  ROLE_ADMIN }
              - { path: ^/user, role:  ROLE_USER }
              - { path: ^/order, role:  IS_AUTHENTICATED_FULLY }
              - { path: ^/, role:  IS_AUTHENTICATED_ANONYMOUSLY }
