# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.doctrine_listener:
        class: AppBundle\Listener\PasswordListener
        arguments: ['@security.password_encoder']
        tags:
            - { name: doctrine.event_subscriber }
